### ISSUE TITLE
Bug in colors.py

### ISSUE THREAD

**Issue by CodeMaxx** [zscproject/OWASP-ZSC-API#1]
The if conditions after [line 16](https://github.com/zscproject/OWASP-ZSC-API/blob/master/core/color.py#L16) are never reached.

**Comment by CodeMaxx** [comment]
Ok I have fixed this...I'll send the patch with the same PR which makes index.py python3 compatible.

**Comment by Ali-Razmjoo** [comment]
as I told you, we need to remove colors before printing in http server. thanks.
